# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02903d6996ba62f8709228bdef241796427c5626e234b582c38284023ef4c93a9b31e3887ff5faca3acc2d3f1dbe3ee1386eed69098d7d76356d0df7a31ca6ea

test:
  secret_key_base: a40aef0fe28af06ee6c99925713aa163aca25eee5575d958db8c734aa8217428dfd74685994b22b4e9b4d2a9a8f9e3936bdd3fc60d7789a477260c0d0519feb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
